In [31]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('housing.csv')

In [9]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [14]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [17]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [20]:
bay_houses = df[df['ocean_proximity'] == "NEAR BAY"]
average_value_near_bay = bay_houses['median_house_value'].mean()

average_value_near_bay 

259212.31179039303

In [21]:
total_bedrooms_average = df['total_bedrooms'].mean()

total_bedrooms_average

537.8705525375618

In [25]:
df['total_bedrooms'].fillna(total_bedrooms_average, inplace=True)

new_total_bedrooms_average = df['total_bedrooms'].mean()
new_total_bedrooms_average

537.8705525375617

In [24]:
df.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [27]:
islands_options = df[df['ocean_proximity'] == 'ISLAND']

islands_options = islands_options[['housing_median_age', 'total_rooms', 'total_bedrooms']]
islands_options

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [65]:
X = islands_options.to_numpy()

X_Transpose = X.T

XTX = np.dot(X_Transpose, X)
XTX_inverse = np.linalg.inv(XTX)

y = np.array([950, 1300, 800, 1000, 1300])

In [67]:
w = np.dot(np.dot(XTX_inverse, X_Transpose), y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [53]:
XTX_inverse

array([[ 3.88139994e+10, -1.84879374e+10,  2.90187188e+09,
         7.54139977e+10, -1.43414843e+11],
       [-5.94615266e+10,  3.50542952e+10, -1.17064716e+10,
        -1.11656742e+11,  2.13707758e+11],
       [ 4.70979471e+10, -2.96946763e+10,  1.13531824e+10,
         8.73300933e+10, -1.67553508e+11],
       [ 5.18302291e+10, -2.08132982e+10, -3.04261339e+08,
         1.02934124e+11, -1.94961295e+11],
       [-1.06904957e+11,  4.49229529e+10, -1.52268678e+09,
        -2.11164367e+11,  4.00350590e+11]])

In [66]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [68]:
pd.__version__

'2.0.3'